<!-- Message de notification -->

<!-- Code HTML à écrire -->
<nav class="user-interface"> 
	<button class="button button-primary"><a href="<?= $requestUrl ?>/compte">creer un compte</a></button>

	<button class="button button-primary"><a href="<?= $requestUrl ?>/connexion">connexion</a></button>
</nav>

<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody class="meal-list">
        <!-- Code HTML à écrire -->
		<?php
		var_dump($products);
		?>


			<?php foreach ($products as $product) : ?>
				<tr>
					<td class="link-list"><img src="<?= $wwwUrl ?>/images/meals/<?=$product['url']?>" alt="<?= $product['url'] ?>"></td>
					<td><em><?= $product['name'] ?></em></td>
					<td><p><?= $product['description'] ?></p></td>
					<td><p><?= $product['priceHT'] ?></p></td>
				</tr>      	
			<?php endforeach; ?>

    </tbody>
</table>