<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody class="meal-list">
        <!-- Code HTML à écrire -->
		<?php foreach ($products as $product) : ?>
			<tr>
				<td class="link-list"><img src="<?= $wwwUrl ?>/images/meals/<?=$product['photo']?>" alt="<?= $product['photo'] ?>"></td>
				<td><h4><?= $product['name'] ?></h4></td>
				<td><p><?= $product['description'] ?></p></td>
				<td><p><?= Tools::formatPrice($product['priceHT']) ?></p></td>
			</tr>      	
		<?php endforeach; ?>

    </tbody>
</table>
