<!-- Message de notification -->

<!-- Code HTML à écrire -->
<nav class="user-interface"> 
	<a href="#">creer un compte</a>
	<a href="#">connexion</a>
</nav>

<!-- Liste des aliments -->
<h3><i></i>Se connecter avec un commte utilisateur</h3>
<form method="post" action="">
	<fieldset>
		<legend>Informations d'authentification</legend>
		<ul>
			<li>
				<label for="mail">e-mail :</label>
				<input type="text" id="mail" values="email">
			</li>
			<li>
				<label for="password">Mot de passe:</label>
				<input type="text" id="password">
			</li>
		</ul>
	</fieldset>
	<a href="<?= $requestUrl ?>">Créer le compte</a>
	<a href=""></a>
</form>