<!-- Message de notification -->


<!-- Liste des aliments -->
<h3><i></i>Passer une commande</h3>
<form method="post" class="generic-form" action="<?= $requestUrl ?>/commande">
	<fieldset>
		<legend>Ajouter un article</legend>
		<ul>
			<li>
				<label for="Article">Article:</label>
				<select id="choiceProduct" name="product_id">
					<?php foreach ($products as $product) : ?>
						<option value="<?= $product['id'] ?>"><?= $product['name'] ?></option>
					<?php endforeach; ?>
				</select>
			</li>
			<li id="meal-details" class="meal-details no-left-label">
			<!-- javascript fiche produit -->
			</li>
			<li>
				<label for="quantity">Quantité:</label>
				<input type="text" name="quantity" id="quantity">
			</li>
			<li>
				<button class="button button-primary" name="button" value="ajout">Ajouter</button>
			</li>
		</ul>
	</fieldset>
	<fieldset>
		<legend>Récapitulatif de la commande</legend>
		<section id="recapCde">
		<!-- javascript panier -->
		</section>
	</fieldset>
	<button class="button button-primary" name="button" value="validation">Validation de la commande</button>
	<button class="button button-cancel" name="button" value="abandon">Abandonner</button>
</form>
<script src="<?= $wwwUrl ?>/js/commande.js"></script>
