<!-- Message de notification -->

<!-- Code HTML à écrire -->

<!-- Réservation d'une table-->
<h3><i></i>Réservation d'une table</h3>
<form method="post" action="<?= $requestUrl ?>/booking">
	<fieldset>
		<legend>Informations</legend>
		<ul>
			<li>
				<label for="dateResa">Date de réservation :</label>
				<select name="resaJ" >
					<option></option>
					<?php for ($i = 1 ; $i<32 ; $i++) : ?>
						<option values="<?= $i ?>"><?= $i ?></option>
					<?php endfor ?>
				</select>
				<select name="resaM">
					<option></option>
					<?php for ($i = 1 ; $i<13 ; $i++) : ?>
						<option values="<?= $i ?>"><?= $i ?></option>
					<?php endfor ?>
				</select>
				<select name="resaA" >
					<option></option>
					<?php for ($i = 2019 ; $i<2020 ; $i++) : ?>
						<option values="<?= $i ?>"><?= $i ?> </option>
					<?php endfor ?>
				</select>
			</li>
			<li>
				<label for="heureResa">Heure de réservation :</label>
				<select name="resaH" >
					<option></option>
					<?php for ($i = 12 ; $i<21 ; $i++) : ?>
						<option values="<?= $i ?>"><?= $i ?></option>
					<?php endfor ?>
				</select>
			</li>
			<li>
				<label for="nbseat">Nombre de couverts :</label>
				<input type="text" id="nbseat" name="seat_number">
			</li>
		</ul>
	</fieldset>
	<button class="button button-primary" name="button" value="book">Réserver</button>
	<button class="button button-cancel" name="button" value="abandon">Abandonner</button>
</form>